    WarmUp0,
    WarmUp1,
    WarmUp2,
    WarmUp3,
    WarmUp4,
    WarmUp5,
    WarmUp6,
    WarmUp7,
    WarmUp8,
    WarmUp9,
    WarmUp10,
    WarmUp11,
    WarmUp12,
    WarmUp13,
    WarmUp14,
    WarmUp15,
    InstFetch0,
    InstFetch1,
    InstFetch2,
    InstFetch3,
    InstFetch4,
    InstFetch5,
    WarmUp0,
    WarmUp1,
    WarmUp2,
    Boot1,
    Boot2,
    Fetch,
    WaitForInterrupt,
    Stop,
    NotReady,
    Interrupt1,
    InstLDAimm2,
    InstLDAzpg2, InstLDAzpg3,
    InstLDAzpgx2, InstLDAzpgx3, InstLDAzpgx4,
    InstLDAabs2, InstLDAabs3, InstLDAabs4,
    InstLDAabsx2, InstLDAabsx3, InstLDAabsx4, InstLDAabsx5,
    InstLDAabsy2, InstLDAabsy3, InstLDAabsy4, InstLDAabsy5,
    InstLDAindx2, InstLDAindx3, InstLDAindx4, InstLDAindx5, InstLDAindx6,
    InstLDAindy2, InstLDAindy3, InstLDAindy4, InstLDAindy5, InstLDAindy6,
    InstLDAind2, InstLDAind3, InstLDAind4, InstLDAind5,
    InstLDXimm2,
    InstLDXzpg2, InstLDXzpg3,
    InstLDXzpgy2, InstLDXzpgy3, InstLDXzpgy4,
    InstLDXabs2, InstLDXabs3, InstLDXabs4,
    InstLDXabsy2, InstLDXabsy3, InstLDXabsy4, InstLDXabsy5,
    InstLDYimm2,
    InstLDYzpg2, InstLDYzpg3,
    InstLDYzpgx2, InstLDYzpgx3, InstLDYzpgx4,
    InstLDYabs2, InstLDYabs3, InstLDYabs4,
    InstLDYabsx2, InstLDYabsx3, InstLDYabsx4, InstLDYabsx5,
    InstSTAzpg2, InstSTAzpg3,
    InstSTAzpgx2, InstSTAzpgx3, InstSTAzpgx4,
    InstSTAabs2, InstSTAabs3, InstSTAabs4,
    InstSTAabsx2, InstSTAabsx3, InstSTAabsx4, InstSTAabsx5,
    InstSTAabsy2, InstSTAabsy3, InstSTAabsy4, InstSTAabsy5,
    InstSTAindx2, InstSTAindx3, InstSTAindx4, InstSTAindx5, InstSTAindx6,
    InstSTAindy2, InstSTAindy3, InstSTAindy4, InstSTAindy5, InstSTAindy6,
    InstSTAind2, InstSTAind3, InstSTAind4, InstSTAind5,
    InstSTXzpg2, InstSTXzpg3,
    InstSTXzpgy2, InstSTXzpgy3, InstSTXzpgy4,
    InstSTXabs2, InstSTXabs3, InstSTXabs4,
    InstSTYzpg2, InstSTYzpg3,
    InstSTYzpgx2, InstSTYzpgx3, InstSTYzpgx4,
    InstSTYabs2, InstSTYabs3, InstSTYabs4,
    InstSTZzpg2, InstSTZzpg3,
    InstSTZzpgx2, InstSTZzpgx3, InstSTZzpgx4,
    InstSTZabs2, InstSTZabs3, InstSTZabs4,
    InstSTZabsx2, InstSTZabsx3, InstSTZabsx4, InstSTZabsx5,
    InstTAXimp2,
    InstTAYimp2,
    InstTSXimp2,
    InstTXAimp2,
    InstTXSimp2,
    InstTYAimp2,
    InstPHAimp2, InstPHAimp3,
    InstPHPimp2, InstPHPimp3,
    InstPHXimp2, InstPHXimp3,
    InstPHYimp2, InstPHYimp3,
    InstPLAimp2, InstPLAimp3, InstPLAimp4,
    InstPLPimp2, InstPLPimp3, InstPLPimp4,
    InstPLXimp2, InstPLXimp3, InstPLXimp4,
    InstPLYimp2, InstPLYimp3, InstPLYimp4,
    InstASLacc2,
    InstASLzpg2, InstASLzpg3, InstASLzpg4, InstASLzpg5,
    InstASLzpgx2, InstASLzpgx3, InstASLzpgx4, InstASLzpgx5, InstASLzpgx6,
    InstASLabs2, InstASLabs3, InstASLabs4, InstASLabs5, InstASLabs6,
    InstASLabsx2, InstASLabsx3, InstASLabsx4, InstASLabsx5, InstASLabsx6, InstASLabsx7,
    InstLSRacc2,
    InstLSRzpg2, InstLSRzpg3, InstLSRzpg4, InstLSRzpg5,
    InstLSRzpgx2, InstLSRzpgx3, InstLSRzpgx4, InstLSRzpgx5, InstLSRzpgx6,
    InstLSRabs2, InstLSRabs3, InstLSRabs4, InstLSRabs5, InstLSRabs6,
    InstLSRabsx2, InstLSRabsx3, InstLSRabsx4, InstLSRabsx5, InstLSRabsx6, InstLSRabsx7,
    InstROLacc2,
    InstROLzpg2, InstROLzpg3, InstROLzpg4, InstROLzpg5,
    InstROLzpgx2, InstROLzpgx3, InstROLzpgx4, InstROLzpgx5, InstROLzpgx6,
    InstROLabs2, InstROLabs3, InstROLabs4, InstROLabs5, InstROLabs6,
    InstROLabsx2, InstROLabsx3, InstROLabsx4, InstROLabsx5, InstROLabsx6, InstROLabsx7,
    InstRORacc2,
    InstRORzpg2, InstRORzpg3, InstRORzpg4, InstRORzpg5,
    InstRORzpgx2, InstRORzpgx3, InstRORzpgx4, InstRORzpgx5, InstRORzpgx6,
    InstRORabs2, InstRORabs3, InstRORabs4, InstRORabs5, InstRORabs6,
    InstRORabsx2, InstRORabsx3, InstRORabsx4, InstRORabsx5, InstRORabsx6, InstRORabsx7,
    InstANDimm2,
    InstANDzpg2, InstANDzpg3,
    InstANDzpgx2, InstANDzpgx3, InstANDzpgx4,
    InstANDabs2, InstANDabs3, InstANDabs4,
    InstANDabsx2, InstANDabsx3, InstANDabsx4, InstANDabsx5,
    InstANDabsy2, InstANDabsy3, InstANDabsy4, InstANDabsy5,
    InstANDindx2, InstANDindx3, InstANDindx4, InstANDindx5, InstANDindx6,
    InstANDindy2, InstANDindy3, InstANDindy4, InstANDindy5, InstANDindy6,
    InstANDind2, InstANDind3, InstANDind4, InstANDind5,
    InstBITimm2,
    InstBITzpg2, InstBITzpg3,
    InstBITzpgx2, InstBITzpgx3, InstBITzpgx4,
    InstBITabs2, InstBITabs3, InstBITabs4,
    InstBITabsx2, InstBITabsx3, InstBITabsx4, InstBITabsx5,
    InstEORimm2,
    InstEORzpg2, InstEORzpg3,
    InstEORzpgx2, InstEORzpgx3, InstEORzpgx4,
    InstEORabs2, InstEORabs3, InstEORabs4,
    InstEORabsx2, InstEORabsx3, InstEORabsx4, InstEORabsx5,
    InstEORabsy2, InstEORabsy3, InstEORabsy4, InstEORabsy5,
    InstEORindx2, InstEORindx3, InstEORindx4, InstEORindx5, InstEORindx6,
    InstEORindy2, InstEORindy3, InstEORindy4, InstEORindy5, InstEORindy6,
    InstEORind2, InstEORind3, InstEORind4, InstEORind5,
    InstORAimm2,
    InstORAzpg2, InstORAzpg3,
    InstORAzpgx2, InstORAzpgx3, InstORAzpgx4,
    InstORAabs2, InstORAabs3, InstORAabs4,
    InstORAabsx2, InstORAabsx3, InstORAabsx4, InstORAabsx5,
    InstORAabsy2, InstORAabsy3, InstORAabsy4, InstORAabsy5,
    InstORAindx2, InstORAindx3, InstORAindx4, InstORAindx5, InstORAindx6,
    InstORAindy2, InstORAindy3, InstORAindy4, InstORAindy5, InstORAindy6,
    InstORAind2, InstORAind3, InstORAind4, InstORAind5,
    InstTRBzpg2, InstTRBzpg3, InstTRBzpg4, InstTRBzpg5,
    InstTRBabs2, InstTRBabs3, InstTRBabs4, InstTRBabs5, InstTRBabs6,
    InstTSBzpg2, InstTSBzpg3, InstTSBzpg4, InstTSBzpg5,
    InstTSBabs2, InstTSBabs3, InstTSBabs4, InstTSBabs5, InstTSBabs6,
    InstADCimm2, InstADCimm3,
    InstADCzpg2, InstADCzpg3, InstADCzpg4,
    InstADCzpgx2, InstADCzpgx3, InstADCzpgx4, InstADCzpgx5,
    InstADCabs2, InstADCabs3, InstADCabs4, InstADCabs5,
    InstADCabsx2, InstADCabsx3, InstADCabsx4, InstADCabsx5, InstADCabsx6,
    InstADCabsy2, InstADCabsy3, InstADCabsy4, InstADCabsy5, InstADCabsy6,
    InstADCindx2, InstADCindx3, InstADCindx4, InstADCindx5, InstADCindx6, InstADCindx7,
    InstADCindy2, InstADCindy3, InstADCindy4, InstADCindy5, InstADCindy6, InstADCindy7,
    InstADCind2, InstADCind3, InstADCind4, InstADCind5, InstADCind6,
    InstCMPimm2,
    InstCMPzpg2, InstCMPzpg3,
    InstCMPzpgx2, InstCMPzpgx3, InstCMPzpgx4,
    InstCMPabs2, InstCMPabs3, InstCMPabs4,
    InstCMPabsx2, InstCMPabsx3, InstCMPabsx4, InstCMPabsx5,
    InstCMPabsy2, InstCMPabsy3, InstCMPabsy4, InstCMPabsy5,
    InstCMPindx2, InstCMPindx3, InstCMPindx4, InstCMPindx5, InstCMPindx6,
    InstCMPindy2, InstCMPindy3, InstCMPindy4, InstCMPindy5, InstCMPindy6,
    InstCMPind2, InstCMPind3, InstCMPind4, InstCMPind5,
    InstCPXimm2,
    InstCPXzpg2, InstCPXzpg3,
    InstCPXabs2, InstCPXabs3, InstCPXabs4,
    InstCPYimm2,
    InstCPYzpg2, InstCPYzpg3,
    InstCPYabs2, InstCPYabs3, InstCPYabs4,
    InstSBCimm2, InstSBCimm3,
    InstSBCzpg2, InstSBCzpg3, InstSBCzpg4,
    InstSBCzpgx2, InstSBCzpgx3, InstSBCzpgx4, InstSBCzpgx5,
    InstSBCabs2, InstSBCabs3, InstSBCabs4, InstSBCabs5,
    InstSBCabsx2, InstSBCabsx3, InstSBCabsx4, InstSBCabsx5, InstSBCabsx6,
    InstSBCabsy2, InstSBCabsy3, InstSBCabsy4, InstSBCabsy5, InstSBCabsy6,
    InstSBCindx2, InstSBCindx3, InstSBCindx4, InstSBCindx5, InstSBCindx6, InstSBCindx7,
    InstSBCindy2, InstSBCindy3, InstSBCindy4, InstSBCindy5, InstSBCindy6, InstSBCindy7,
    InstSBCind2, InstSBCind3, InstSBCind4, InstSBCind5, InstSBCind6,
    InstDECacc2,
    InstDECzpg2, InstDECzpg3, InstDECzpg4, InstDECzpg5,
    InstDECzpgx2, InstDECzpgx3, InstDECzpgx4, InstDECzpgx5, InstDECzpgx6,
    InstDECabs2, InstDECabs3, InstDECabs4, InstDECabs5, InstDECabs6,
    InstDECabsx2, InstDECabsx3, InstDECabsx4, InstDECabsx5, InstDECabsx6, InstDECabsx7,
    InstDEXimp2,
    InstDEYimp2,
    InstINCacc2,
    InstINCzpg2, InstINCzpg3, InstINCzpg4, InstINCzpg5,
    InstINCzpgx2, InstINCzpgx3, InstINCzpgx4, InstINCzpgx5, InstINCzpgx6,
    InstINCabs2, InstINCabs3, InstINCabs4, InstINCabs5, InstINCabs6,
    InstINCabsx2, InstINCabsx3, InstINCabsx4, InstINCabsx5, InstINCabsx6, InstINCabsx7,
    InstINXimp2,
    InstINYimp2,
    InstBRArel2, InstBRArel3, InstBRArel4,
    InstBRKimp2, InstBRKimp3, InstBRKimp4, InstBRKimp5, InstBRKimp6, InstBRKimp7,
    InstJMPabs2, InstJMPabs3,
    InstJMPind2, InstJMPind3, InstJMPind4, InstJMPind5,
    InstJSRabs2, InstJSRabs3, InstJSRabs4, InstJSRabs5, InstJSRabs6,
    InstRTIimp2, InstRTIimp3, InstRTIimp4, InstRTIimp5, InstRTIimp6,
    InstRTSimp2, InstRTSimp3, InstRTSimp4, InstRTSimp5, InstRTSimp6,
    InstCLCimp2,
    InstCLDimp2,
    InstCLIimp2,
    InstCLVimp2,
    InstSECimp2,
    InstSEDimp2,
    InstSEIimp2,
    InstBCCrel2, InstBCCrel3, InstBCCrel4,
    InstBCSrel2, InstBCSrel3, InstBCSrel4,
    InstBEQrel2, InstBEQrel3, InstBEQrel4,
    InstBMIrel2, InstBMIrel3, InstBMIrel4,
    InstBNErel2, InstBNErel3, InstBNErel4,
    InstBPLrel2, InstBPLrel3, InstBPLrel4,
    InstBVCrel2, InstBVCrel3, InstBVCrel4,
    InstBVSrel2, InstBVSrel3, InstBVSrel4,
    InstSTPimp2, InstSTPimp3,
    InstWAIimp2, InstWAIimp3,
    InstNOP2, InstNOP3, InstNOP4, InstNOP5, InstNOP6, InstNOP7, InstNOP8;

    public static States FromValue(int value)
    {
        States[] states = (States[])Enum.GetValues(typeof(States));
        foreach (States state in states)
        {
            if ((int)state == value)
                return state;
        }
        return States.WarmUp0;
    }
    InstJsrabs2, InstJsrabs3, InstJsrabs4, InstJsrabs5, InstJsrabs6,

    InstRtiimp2, InstRtiimp3, InstRtiimp4, InstRtiimp5, InstRtiimp6,

    InstRtsimp2, InstRtsimp3, InstRtsimp4, InstRtsimp5, InstRtsimp6,

    InstClcimp2,
    InstCldimp2,
    InstCliimp2,
    InstClvimp2,
    InstSecimp2,
    InstSedimp2,
    InstSeiimp2,

    InstBccrel2, InstBccrel3, InstBccrel4,
    InstBcsrel2, InstBcsrel3, InstBcsrel4,
    InstBeqrel2, InstBeqrel3, InstBeqrel4,
    InstBmirel2, InstBmirel3, InstBmirel4,
    InstBnerel2, InstBnerel3, InstBnerel4,
    InstBplrel2, InstBplrel3, InstBplrel4,
    InstBvcrel2, InstBvcrel3, InstBvcrel4,
    InstBvsrel2, InstBvsrel3, InstBvsrel4,

    InstStpimp2, InstStpimp3,

    InstWaiimp2, InstWaiimp3,

    InstNop2, InstNop3, InstNop4, InstNop5, InstNop6, InstNop7, InstNop8;

    public static States FromValue(int value)
    {
        States[] states = (States[])Enum.GetValues(typeof(States));
        foreach (States state in states)
        {
            if ((int)state == value)
                return state;
        }
        return States.WarmUp0;
    }
